nginx-proxy:
  build: ../images/proxy
  container_name: proxy
  links:
    - sinopia
    - teamcity
  ports:
    - 80:80
    - 443:443
  restart: always
  volumes:
    - /usr/share/data-services/certs:/etc/nginx/certs
    - /var/run/docker.sock:/tmp/docker.sock:ro

sinopia:
  build: ../images/sinopia
  container_name: sinopia
  env_file: /etc/infrastructure/env/sinopia.env
  restart: always
  volumes:
    - /usr/share/data-services/sinopia:/data/sinopia

teamcity:
  build: ../images/teamcity
  container_name: teamcity
  env_file: /etc/infrastructure/env/teamcity.env
  links:
    - teamcity-data
  restart: always
  volumes:
    - /usr/share/data-services/teamcity:/var/lib/teamcity

teamcity-agent:
  build: ../images/teamcity-agent
  container_name: teamcity-agent
  env_file: /etc/infrastructure/env/teamcity-agent.env
  links:
    - teamcity
  restart: always
  volumes:
    - /usr/share/data-services/teamcity-agent:/opt/buildAgent

teamcity-data:
  image: postgres:latest
  container_name: teamcity-data
  env_file: /etc/infrastructure/env/teamcity-data.env
  restart: always
  volumes:
    - /usr/share/data-services/teamcity-data:/teamcity
